sample_kbs/src/enc_mods/offline_fs_kbs/generate_keys.sh

`dd bs=32 count=1 if=/dev/random` doesn't always do what I thought it
did (the block might not actually get filled and the key will be too
short). Use `head`.
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

offline_fs_kbs: Do not use dd in generate-keys.sh

---

src/kbc_modules/eaa_kbc/mod.rs
src/kbc_modules/eaa_kbc/rats_tls/mod.rs
src/kbc_modules/mod.rs

The rats-tls relied on by EAA KBC adds the function of automatic detection platform and selecting appropriate attester (rats-tls PR#1452: https://github.com/alibaba/inclavare-containers/pull/1452 ）Therefore, we no longer need to hard code the parameter ‘tdx’ attester in EAA KBC.

EAA KBC: Remove hardcode 'tdx' field

---

.github/workflows/offline_sev_kbc.yml

Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
----
Following #27 , add a build "job" for the offline_sev_kbc. It builds and runs the rust tests with `--feature offline_sev_kbc`. 
How can we test this?
cc: @fitzthum

CI/CD: offline_sev_kbc CI

---

src/grpc/mod.rs
src/grpc/protocol/keyprovider_structs.rs
src/main.rs

Simplified `parse_input()` drastically by implementing `TryFrom` for
`InputPayload` and `KeyProviderInput`.
Also refactored error handling and added lots of unit tests.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

agent: Simplify code using TryFrom trait

---

.github/workflows/offline_sev_kbc.yml

Signed-off-by: Dov Murik <dovmurik@linux.ibm.com>
---
This should solve the CI issues we see in Nightly and Beta in #33 :
```
error: 'rustfmt' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
```

CI: Add rustfmt to offline_sev_kbc job

---

src/grpc/mod.rs

After the version of rust is updated, the following problems will occur when compiling AA:
```shell
cargo build --release --no-default-features --features sample_kbc 
Compiling attestation-agent v1.0.0 (/root/xinjian/attestation-agent)
error[E0308]: mismatched types
--> src/grpc/mod.rs:120:9
|
120 |         Ok(Response::new(reply))
|         ^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Status`, found struct `anyhow::Error`
|
= note: expected enum `std::result::Result<_, Status>`
found enum `std::result::Result<_, anyhow::Error>`
note: return type inferred to be `std::result::Result<tonic::Response<KeyProviderKeyWrapProtocolOutput>, Status>` here
--> src/grpc/mod.rs:55:69
|
55  |       ) -> Result<Response<KeyProviderKeyWrapProtocolOutput>, Status> {
| …
```

Fix: src/grpc/mod.rs: expected struct `Status`, found struct `anyhow:Error`.

---

Makefile

The commit 1f3e58da2b97349b28a3ed4c added Cargo.lock in version
control so we should not delete that file on `make clean`
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

makefile: do not remove Cargo.lock on `make clean`

---

sample_kbs/README.md

On sample_kbs's README tell how to copy an image to the current directory
as it might not be obvious to newcomers.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

sample_kbs: add instruction to copy image to localhost

---

Cargo.toml
app/Cargo.lock
app/Cargo.toml
app/src/grpc/getresource/mod.rs
app/src/grpc/keyprovider/mod.rs
app/src/main.rs
src/kbc_modules/cc_kbc/mod.rs
src/kbc_modules/eaa_kbc/mod.rs
src/kbc_modules/mod.rs
src/kbc_modules/offline_fs_kbc/mod.rs
src/kbc_modules/offline_sev_kbc/mod.rs
src/kbc_modules/sample_kbc/mod.rs
src/lib.rs

The upcoming `online_sev_kbc` and `CC-KBC` will need async support. This should enable it. 
I think that we should probably rework our usage of the mutex in the gRPC functions at some point. For now I'm just leaving it as it is. This isn't really a performance-sensitive application, but I think it's still non-optimal.
The `eaa-kbc` seems a little bit broken right now. As you can see the test has some problem. There are also a few clippy warnings that should be fixed at some point.
@dubek

Make AA and KBC traits async

---

src/kbc_modules/sample_kbc/policy.json

Due to https://github.com/confidential-containers/image-rs/issues/40
in image-rs, the field `scheme` specifying
the signing scheme is abandoned now.
This issue here will block https://github.com/confidential-containers/image-rs/issues/43

Sample KBC: delete unused field scheme

---

src/kbc_modules/offline_sev_kbc/README.md
src/kbc_modules/offline_sev_kbc/mod.rs
src/kbc_modules/online_sev_kbc/README.md
src/kbc_modules/online_sev_kbc/mod.rs

In preparation for the first release, which will use the upstream 5.19 kernel and a Ubuntu 20.04 rootfs for SEV, we need a few minor changes.
@dubek

Tweaks for first release with 5.19 kernel

---

src/kbc_modules/online_sev_kbc/mod.rs

Requests resources from KBS by resource name/type.
This is a bit tricky to test end-to-end given that `image-rs` support in Kata isn't upstream yet. I think we will stick with the offline KBS for the first release.
This just uses the name of the resource to make the request, but it looks like we're really treating the name of the resource more like the type of the resource. I suspect we might want to add support for an additional resource id in the future. 
@dubek 
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>

Add get_resource support to online_sev_kbc

---

src/common/mod.rs
src/common/sev/mod.rs
src/kbc_modules/offline_sev_kbc/mod.rs
src/kbc_modules/online_sev_kbc/mod.rs
src/lib.rs

This pulls out some common code that was duplicated between `offline_sev_kbc` and `online_sev_kbc`.
In the past we have put common code into separate files in the KBC modules. That never really worked very well so I created a new module for shared components that should be a bit more flexible.
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>

Extract common SEV code

---

.github/workflows/sample_keyprovider.yml
.github/workflows/sev_kbc.yml

We didn't have coverage for the `online_sev_kbc` or `sample_keyprovider`.

FIxup CI coverage

---

src/kbc_modules/eaa_kbc/rats_tls/mod.rs

EAA KBC does not use the callback function of rats-tls, so it can be set to None directly. (If do not do this, errors will occur when compiling on the TDX platform.)

EAA KBC: Fix compile bug of rats-tls callback on TDX.

---

src/lib.rs

Somehow I missed these warnings. This should resolve them.
Signed-off-by: Tobin Feldman-Fitzthum <tobin@ibm.com>

Fix dead code warnings

---

src/kbc_modules/cc_kbc/crypto/mod.rs
src/kbc_modules/mod.rs
src/kbc_modules/online_sev_kbc/mod.rs

The Client Id resource type allows a guest to request an Id that is provided by the KBS. This can allow a client to more easily associate a particular KBC/workload with a KBS. This value has a somewhat limited use because it cannot be shared publicly. Nonetheless it seems handy and is trivial to implement for SEV.
@dubek

Introduce Client Id resource 

---

Cargo.lock
Cargo.toml

This pulls in the following fix which affects building the tdx-attest-sys crates when libclang is avilable but clang is not: https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/28

Update tdx-attest-rs crate for buildgen build fix

---

app/src/grpc.rs
app/src/rpc/mod.rs
app/src/ttrpc.rs
src/kbc_modules/mod.rs
src/lib.rs

When running `attestation-agent --help`, print information about the protocol (grpc/ttrpc) and the built-in KBCs.
----
Example:
```
$ make KBC=online_sev_kbc,offline_fs_kbc,sample_kbc ttrpc=true
DEBIANOS is: true
cd app &&  cargo build --release --no-default-features --features " online_sev_kbc,offline_fs_kbc,sample_kbc ttrpc,rust-crypto" --target x86_64-unknown-linux-gnu
Compiling attestation-agent v0.1.0 (/home/dubek/dev/attestation-agent/app)
Finished release [optimized] target(s) in 3.33s
$ app/target/x86_64-unknown-linux-gnu/release/attestation-agent --help
attestation-agent 0.1.0
Protocol: ttrpc
KBCs: offline_fs_kbc, online_sev_kbc, sample_kbc
USAGE:
attestation-agent [OPTIONS]
OPTIONS:
...
...
```
Cc: @fitzthum

feat: Add protocol and KBCs info to `--help` output

---

app/Cargo.lock
src/kbc_modules/cc_kbc/attester/tdx/mod.rs

In certain versions of the TDX guest kernel, due to interface changes, the `/dev/tdx-attest` driver has been renamed as the `/dev/tdx-guest` driver.

CC-KBC-TDX: Update detect_platform.

---

app/Cargo.toml
app/src/rpc/getresource/mod.rs
app/src/rpc/keyprovider/mod.rs
app/src/ttrpc.rs
protos/getresource.proto
src/kbc_modules/uri.rs
src/lib.rs

When doing integration test, some bugs occurs and this pr can fix.
As the `reqwest` crate will not automatically try `http` when `https` fails, we must specify the KBS address by `aa_params`. That parameter will be delivered from the gRPC request.

Fix cckbc uri scheme

---

src/kbc_modules/uri.rs

some kbcs might not provide a port number. In this case the parsing a socket addr will cause an unexpected error

fix: delete useless parsing of socket addr

---

coco_keyprovider/src/enc_mods/mod.rs

When a kid is generated automatically, current inplementation will raise an error that the kid is not legal.

fix: automatically generated kid

---

.github/workflows/basic.yml
app/Cargo.toml
app/src/main.rs
app/src/rpc/ttrpc_protocol/mod.rs
app/src/ttrpc.rs

Now the Rust lint does not cover all  the sub crates, and I get the following errors when execute `cargo clippy` but they are not reported by CI
```
warning: redundant field names in struct initialization
--> app/src/rpc/ttrpc_protocol/getresource_ttrpc.rs:33:13
|
33 |             client: client,
|             ^^^^^^^^^^^^^^ help: replace it with: `client`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
= note: `#[warn(clippy::redundant_field_names)]` on by default
warning: redundant field names in struct initialization
--> app/src/rpc/ttrpc_protocol/keyprovider_ttrpc.rs:33:13
|
33 |             client: client,
|             ^^^^^^^^^^^^^^ help: replace it with: `client`
|
= help: for further information visit …
```

Let Rust lint CI cover all sub crates

---

coco_keyprovider/README.md

While ago I had to encrypt an image to use with SEV and I got some difficult to understand the new coco_keyprovider by only reading the README. As I learned I took some notes and now I am flushing on the README.
---
Applied major changes in coco_keyprovider's README.md aiming to explain basic concepts and ease for non-experts on the domain.

coco_keyprovider: rewrite the README.md

---

README.md

Development has shifted to the converged image-rs repo.
I can update that name with a new commit if we change the image-rs repo name. But I'd like to quickly redirect people so they don't waste time / get frustrated with this repo.

Document repo archival
